openapi: 3.0.0
info:
  title: API Becommerce - Anuncio
  description: Api oficial da Becommerce para gestão de anuncio
  version: 1.0.0-oas3
servers:
- url: https://virtserver.swaggerhub.com/lfeitosa/ADS/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://k8s.becommerce.com.br/api-externa-anuncio/1.0.0
  description: Servidor usado para testes da API
- url: http://api.becommerce.com.br/anuncio/v1
  description: URL da api de produção
tags:
- name: Price
  description: (price) É a entidade que representa a alteracao do preço de um anúncio.
paths:
  /items/{itemID}:
    put:
      tags:
      - Price
      summary: Realiza a alteração do preço
      parameters:
      - name: itemID
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: MLB1138005551
         
      requestBody:
        description: Envia um objeto que representa um produto com as alterações necessárias
        content:
          application/json:
            schema:
              example: '{"valor": "27.12"}'
        required: true
      responses:
        200:
          description: Retorna o ajuste realizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updatePrice'
        400:
          description: The request contains headers, query params or body attributes empty that are required.
          content:
            text/plain:
              schema:
                type: string
        401:
          description: The access token is missing or invalid.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Resource not found.
          content:
            text/plain:
              schema:
                type: string
        422:
          description: The request contains headers, query params or body attributes with invalid values.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: An error ocurred in the service. Please include the trace identifier in your report.
          content:
            text/plain:
              schema:
                type: string
      security:
      - bearerAuth: []
components:
  schemas:
    updatePrice:
      type: object
      properties:
        item:
          type: string
          format: string
          example: MLB154897563
        price:
          type: number
          format: float
          example: 23.12
        statusRetorno:
          type: string
          format: string
          example: Sucesso
      description: |
        Refere-se alteracao do preço de um anuncio.
  responses:
    BadRequest:
      description: The request contains headers, query params or body attributes empty that are required.
      content:
        text/plain:
          schema:
            type: string
    UnathorizedRequest:
      description: The access token is missing or invalid.
      content:
        text/plain:
          schema:
            type: string
    NotFound:
      description: Resource not found.
      content:
        text/plain:
          schema:
            type: string
    BadContentTypeRequest:
      description: The request contains invalid Content Type.
      content:
        text/plain:
          schema:
            type: string
    AppUpdate:
      description: The mobile application must be updated.
      content:
        text/plain:
          schema:
            type: string
    UnprocessableRequest:
      description: The request contains headers, query params or body attributes with invalid values.
      content:
        text/plain:
          schema:
            type: string
    ServiceError:
      description: An error ocurred in the service. Please include the trace identifier in your report.
      content:
        text/plain:
          schema:
            type: string
    NotImplemented:
      description: Unsupported functionality.
      content:
        text/plain:
          schema:
            type: string
    BadGateway:
      description: An error ocurred in one of the upstreams services, the body contains the description.
      headers:
        X-Upstream-Code:
          description: Error code from the upstream services.
          style: simple
          explode: false
          schema:
            type: string
      content:
        text/plain:
          schema:
            type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
