openapi: 3.0.0
info:
  title: API Becommerce - Produtos
  description: Api oficial da Becommerce para gestão de produtos
  version: 1.0.1
servers:
- url: https://virtserver.swaggerhub.com/lfeitosa/Teste/1.0.1
       
  description: SwaggerHub API Auto Mocking
- url: http://api.becommerce.com.br/v1
  description: URL da api de produção
- url: http://staging-api.becommerce.com.br/v1
  description: Servidor usado para testes da API
tags:
- name: Produtos
  description: (products) É a entidade que representa um produto do seller
- name: Estoque
  description: (stock) É o ajuste da quantidade do produto disponibilizado em anuncio Meli.
paths:
  /products:
    get:
      tags:
      - Produtos
      summary: Obtem uma lista de produtos do sistema
      parameters:
      - name: accountID
        in: header
        description: Refere-se a conta usada na Becommerce, a identificação da Loja
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: TT620483
      - in: header
        name: Authorization⠀
        schema:
          type: string
          format: string
          example: "Basic 20NpoWoylOXJFs5IsrJeQDSAFasdaFASAFfas"
        required: true    
      responses:
        200:
          description: Retorna uma lista de produtos cadastrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
        400:
          description: The request contains headers, query params or body attributes empty that are required.
          content:
            text/plain:
              schema:
                type: string
        401:
          description: The access token is missing or invalid.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Resource not found.
          content:
            text/plain:
              schema:
                type: string
        422:
          description: The request contains headers, query params or body attributes with invalid values.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: An error ocurred in the service. Please include the trace identifier in your report.
          content:
            text/plain:
              schema:
                type: string
      security:
      - bearerAuth: []
    put:
      tags:
      - Estoque
      summary: Realiza uma alteração no estoque em uma entidade ja existente
      security:
      - bearerAuth: []
      parameters: 
        - in: header
          name: Authorization⠀
          schema:
            type: string
            maxLength: 120
            format: string
            example: "Basic%20NpoWoylOXJFs5IsrJeQDSAFasdaFASAFfas"
          required: true
       
      requestBody:
       content:
         application/json:
          schema:
           $ref: '#/components/schemas/UpdStockRequest'
        
      responses:
        200:
          description: Retorno confirmando que o objeto foi alterado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdStockResponse"
        400:
          description: The request contains headers, query params or body attributes empty that are required.
          content:
            text/plain:
              schema:
                type: string
        401:
          description: The access token is missing or invalid.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Resource not found.
          content:
            text/plain:
              schema:
                type: string
        422:
          description: The request contains headers, query params or body attributes with invalid values.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: An error ocurred in the service. Please include the trace identifier in your report.
          content:
            text/plain:
              schema:
                type: string
      
  /products/{productID}:
    get:
      tags:
      - Produtos
      summary: Pega o registro de um produto de acordo com o productID passado
      parameters:
      - name: productID
        in: path
        description: É o identificador unico do produto (MELIID)
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: MLB1138005551
      - name: accountID
        in: header
        description: Refere-se a conta usada na Becommerce, a identificação da Loja
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: TT620483
      - in: header
        name: Authorization⠀
        schema:
          type: string
          format: string
          example: "Basic 20NpoWoylOXJFs5IsrJeQDSAFasdaFASAFfas"
        required: true    
      responses:
        200:
          description: Retorna o produto solicitado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: The request contains headers, query params or body attributes empty that are required.
          content:
            text/plain:
              schema:
                type: string
        401:
          description: The access token is missing or invalid.
          content:
            text/plain:
              schema:
                type: string
        404:
          description: Resource not found.
          content:
            text/plain:
              schema:
                type: string
        422:
          description: The request contains headers, query params or body attributes with invalid values.
          content:
            text/plain:
              schema:
                type: string
        500:
          description: An error ocurred in the service. Please include the trace identifier in your report.
          content:
            text/plain:
              schema:
                type: string
      security:
      - bearerAuth: []
components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  schemas:
    Products:
      $ref: '#/components/schemas/Product'
    UpdStockRequest:
      type: object
      properties:
        qtd:
          type: number
          example: 10
        codSKU:
          type: string
          example: "MLB975556002"
        observacao:
          type: string
          example: "Ajuste de estoque para Becommerce"
        comando:
          type: string
          example: "ajuste"
      description: Atualizacao de estoque dentro da Becommerce (meli).
    UpdStockResponse:
      type: object
      properties:
        qtd:
          type: number
          example: 10
        codSKU:
          type: string
          example: MLB975556002
        observacao:
          type: string
          example: Ajuste de estoque para Becommerce
        comando:
          type: string
          example: ajuste
        statusRetorno:
          type: string
          example: Sucesso
      description: Retorno da atualizacao de estoque dentro da Becommerce (meli).
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 21
        sku:
          type: string
          example: PROD-1234
        title:
          type: string
          example: Iphone 6s Plus
        tags:
          type: string
          example: free_shipping
        sellPrice:
          type: number
          example: 42.32
        costPrice:
          type: number
          example: 20
        checkoutRequest:
          type: string
          example: Qual frete?
        sendTypeProduct:
          type: string
          example: Digital
        expeditionDetails:
          type: string
        hasVariation:
          type: boolean
          example: false
        fiscalGroup:
          type: string
          example: "01"
        comercialUnit:
          type: string
          example: UN
        cfop:
          $ref: '#/components/schemas/CFOP'
        ncm:
          $ref: '#/components/schemas/NCM'
        productOrigin:
          type: string
          example: 0 - Nacional - Exceto as indicadas nos códigos 3 a 5
          enum:
          - 0 - Nacional - Exceto as indicadas nos códigos 3 a 5
          - 1 - Estrangeira - Importação direta, exceto a indicada no cógio 6
        ads:
          type: array
          items:
            type: string
            example: '["MLB2313123","MLB23123123"]'
        variations:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariation'
        inventoryRule:
          type: string
          example: Padrão
        photos:
          type: array
          items:
            $ref: '#/components/schemas/Photo'
        freightInfo:
          $ref: '#/components/schemas/FreightInfo'
        inventories:
          type: array
          items:
            $ref: '#/components/schemas/Inventories'
    ProductVariation:
      type: object
      properties:
        cod_sku:
          type: string
          format: string
          example: PROD-1234
        id_sku:
          type: integer
          example: 32
        grid:
          type: array
          items:
            $ref: '#/components/schemas/DataVariation'
    DataVariation:
      type: object
      properties:
        id_variation:
          type: string
          format: string
          example: MLA21313
        nameVariation:
          type: string
          format: string
          example: Cor
        valueVariation:
          type: string
          format: string
          example: preto
        situationVariation:
          type: string
          format: string
          example: active
        stock:
          type: integer
          format: integer
          example: 12
    Photo:
      type: object
      properties:
        id:
          type: integer
          example: 32
        url:
          type: string
          example: www.google.com.br/img.png
        isMainPhoto:
          type: boolean
          default: false
      description: |
        É a foto do produto, ela pode ser colocada como principal ou não
    CFOP:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
          example: "5350"
        description:
          type: string
          example: PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE
      description: |
        Código Fiscal de Operações e Prestações, das entradas e saídas de mercadorias, intermunicipal e interestadual. Trata-se de um código numérico que identifica a natureza de circulação da mercadoria ou a prestação de serviço de transportes.
    NCM:
      type: object
      properties:
        id:
          type: integer
        code:
          type: string
          example: "123052990"
        description:
          type: string
          example: Outros serviços de assistência social
      description: |
        NCM significa "Nomenclatura Comum do Mercosul" e trata-se de um código de oito dígitos estabelecido pelo Governo Brasileiro para identificar a natureza das mercadorias e promover o desenvolvimento do comércio internacional, além de facilitar a coleta e análise das estatísticas do comércio exterior.
    FreightInfo:
      type: object
      properties:
        id:
          type: integer
          example: 32
        height:
          type: number
          example: 2
        width:
          type: number
          example: 2
        depth:
          type: number
          example: 16
        weight:
          type: string
          example: peso da carga
        timeHandling:
          type: string
          description: Número em dias que será adicionado ao prazo calculado do frete.
          example: "2"
        ownDelivery:
          type: boolean
          description: Define se este item possui a opção de entrega propria.
          default: false
        removal:
          type: boolean
        freightMode:
          type: string
          enum:
          - Correios
          - Tabela Personalizada
          - Mercado Envios
        freightTableID:
          type: integer
          description: Tabela personalizada por grupo de estados, para gerenciar as tabelas da conta, acesse 'Tabelas de Frete > Gerenciamento
          example: 14
        additionalUnity:
          type: number
          description: Define a regra de calculo de frete para mais de uma unidade deste mesmo produto.
          example: 0
        freeNormal:
          type: boolean
        freeExpress:
          type: boolean
        expressAdditionalValue:
          type: number
        expressAdditionalPercent:
          type: number
          example: 23
        normalAdditionalValue:
          type: number
        normalAdditionalPercent:
          type: number
          example: 34.32
      description: |
        São as informações de frete do produto, contém toda a informação necessária para um calculo de frete
    Inventories:
      required:
      - blockMovement
      - id
      - situationInvetorie
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        externalLocator:
          type: string
          format: string
          example: INV-12374
        blockMovement:
          type: boolean
          format: boolean
          example: true
        situationInvetorie:
          type: string
          format: String
          example: Aberto
          enum:
          - Aberto
          - Processado
          - Cancelado
        note:
          type: string
          format: String
          example: Inventario para organizacao da operacao
      description: |
        Metodo destinado para consulta de inventarios da Bec.
  responses:
    BadRequest:
      description: The request contains headers, query params or body attributes empty that are required.
      content:
        text/plain:
          schema:
            type: string
    UnathorizedRequest:
      description: The access token is missing or invalid.
      content:
        text/plain:
          schema:
            type: string
    NotFound:
      description: Resource not found.
      content:
        text/plain:
          schema:
            type: string
    BadContentTypeRequest:
      description: The request contains invalid Content Type.
      content:
        text/plain:
          schema:
            type: string
    AppUpdate:
      description: The mobile application must be updated.
      content:
        text/plain:
          schema:
            type: string
    UnprocessableRequest:
      description: The request contains headers, query params or body attributes with invalid values.
      content:
        text/plain:
          schema:
            type: string
    ServiceError:
      description: An error ocurred in the service. Please include the trace identifier in your report.
      content:
        text/plain:
          schema:
            type: string
    NotImplemented:
      description: Unsupported functionality.
      content:
        text/plain:
          schema:
            type: string
    BadGateway:
      description: An error ocurred in one of the upstreams services, the body contains the description.
      headers:
        X-Upstream-Code:
          description: Error code from the upstream services.
          style: simple
          explode: false
          schema:
            type: string
      content:
        text/plain:
          schema:
            type: string
  
